# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'botInterface.ui'
#
# Created: Mon Jan 27 15:01:41 2020
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(755, 463)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(755, 463))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 261, 391))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 243, 57))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setStyleSheet(_fromUtf8("border-color: rgb(0, 170, 127);"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.verticalLayoutWidget)
        self.line.setStyleSheet(_fromUtf8("background-color: rgba(0, 255, 127, 90);"))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.listView = QtGui.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(10, 80, 241, 301))
        self.listView.setStyleSheet(_fromUtf8("border-color: rgb(0, 170, 127);"))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 10, 291, 391))
        self.groupBox_2.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 170, 127);"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tabelas_de_mensagens = QtGui.QTabWidget(self.groupBox_2)
        self.tabelas_de_mensagens.setGeometry(QtCore.QRect(10, 20, 271, 271))
        self.tabelas_de_mensagens.setObjectName(_fromUtf8("tabelas_de_mensagens"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 271, 251))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.caixa_msg_1 = QtGui.QTextEdit(self.gridLayoutWidget)
        self.caixa_msg_1.setObjectName(_fromUtf8("caixa_msg_1"))
        self.gridLayout_2.addWidget(self.caixa_msg_1, 0, 0, 1, 1)
        self.tabelas_de_mensagens.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 271, 251))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_3.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.tabelas_de_mensagens.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 290, 271, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_5 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_4 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(185, 330, 101, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(10, -1, 6, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_7 = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_7.setStyleSheet(_fromUtf8("background-color: rgba(0, 255, 127, 90);"))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 330, 120, 51))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.listWidget_2 = QtGui.QListWidget(self.groupBox_4)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.listWidget_2.setMaximumSize(QtCore.QSize(150, 40))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(580, 9, 151, 391))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.listWidget = QtGui.QListWidget(self.groupBox_3)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_4.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuEditar = QtGui.QMenu(self.menubar)
        self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
        self.menuSuporte = QtGui.QMenu(self.menubar)
        self.menuSuporte.setObjectName(_fromUtf8("menuSuporte"))
        self.menuTutoriais = QtGui.QMenu(self.menubar)
        self.menuTutoriais.setObjectName(_fromUtf8("menuTutoriais"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuSuporte.menuAction())
        self.menubar.addAction(self.menuTutoriais.menuAction())

        self.retranslateUi(MainWindow)
        self.tabelas_de_mensagens.setCurrentIndex(1)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.caixa_msg_1.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Robô WhatsApp", None))
        self.groupBox.setTitle(_translate("MainWindow", "Área de Contatos do WhatsApp", None))
        self.pushButton_2.setText(_translate("MainWindow", "Abrir arquivo", None))
        self.pushButton.setText(_translate("MainWindow", "Exportar", None))
        self.pushButton_3.setText(_translate("MainWindow", "Importar", None))
        self.label.setText(_translate("MainWindow", "Contatos do WhatsApp", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Área da Menssagem", None))
        self.caixa_msg_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.tabelas_de_mensagens.setTabText(self.tabelas_de_mensagens.indexOf(self.tab), _translate("MainWindow", "Mensagem 1", None))
        self.tabelas_de_mensagens.setTabText(self.tabelas_de_mensagens.indexOf(self.tab_2), _translate("MainWindow", "Mensagem 2", None))
        self.pushButton_5.setText(_translate("MainWindow", "Arquivo", None))
        self.pushButton_6.setText(_translate("MainWindow", "Variável", None))
        self.pushButton_4.setText(_translate("MainWindow", "Apagar", None))
        self.pushButton_7.setText(_translate("MainWindow", "Enviar", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Arquivos", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Ferramentas", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Extrair Contatos", None))
        item.setWhatsThis(_translate("MainWindow", "Extrai contatos de grupos que você participa", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Novo Evento", None))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Gerênciar Eventos", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar", None))
        self.menuSuporte.setTitle(_translate("MainWindow", "Suporte", None))
        self.menuTutoriais.setTitle(_translate("MainWindow", "Tutoriais", None))
